package com.tonypeanut.literalura.repository;

import com.tonypeanut.literalura.model.Libro;
import com.tonypeanut.literalura.model.TodosIdiomas;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

public interface TodosIdiomasRepository extends JpaRepository<TodosIdiomas, Long> {
    @Modifying
    @Transactional
    @Query( value = """
                INSERT INTO todos_idiomas (idioma, iso_639_1, iso_639_2) VALUES
                ('Abkhaz', 'ab', 'abk'),
                ('Afar', 'aa', 'aar'),
                ('Africanos', 'af', 'afr'),
                ('Akan', 'ak', 'aka'),
                ('Albania', 'sq', 'sqi'),
                ('Amárico', 'am', 'amh'),
                ('Árabe', 'ar', 'ara'),
                ('Aragonés', 'an', 'arg'),
                ('Armenio', 'hy', 'hye'),
                ('Assamese', 'as', 'asm'),
                ('Avaric', 'av', 'ava'),
                ('Avestan', 'ae', 'ave'),
                ('Aymara', 'ay', 'aym'),
                ('Azerbaiyán', 'az', 'aze'),
                ('Bambara', 'bm', 'bam'),
                ('Bashkir', 'ba', 'bak'),
                ('Vasco', 'eu', 'eus'),
                ('Belarús', 'be', 'bel'),
                ('Bengalí', 'bn', 'ben'),
                ('Bihari', 'bh', 'bih'),
                ('Bislama', 'bi', 'bis'),
                ('Bosnia', 'bs', 'bos'),
                ('Breton', 'br', 'bre'),
                ('Búlgaro', 'bg', 'bul'),
                ('Burmese', 'my', 'mya'),
                ('Catalán', 'ca', 'cat'),
                ('Chamorro', 'ch', 'cha'),
                ('Chechenio', 'ce', 'che'),
                ('Chichewa, Chewa, Nyanja', 'ny', 'nya'),
                ('Chino', 'zh', 'zho'),
                ('Chuvashia', 'cv', 'chv'),
                ('Cornualles', 'kw', 'cor'),
                ('Corso', 'co', 'cos'),
                ('Cree', 'cr', 'cre'),
                ('Croacia', 'hr', 'hrv'),
                ('Checo', 'cs', 'ces'),
                ('Danés', 'da', 'dan'),
                ('Divehi, Dhivehi, Maldivas', 'dv', 'div'),
                ('Holandés', 'nl', 'nld'),
                ('Dzongkha', 'dz', 'dzo'),
                ('Inglés', 'en', 'eng'),
                ('Esperanto', 'eo', 'epo'),
                ('Estonia', 'et', 'est'),
                ('Ewe', 'ee', 'ewe'),
                ('Faroese', 'fo', 'fao'),
                ('Fiji', 'fj', 'fij'),
                ('Finlandés', 'fi', 'fin'),
                ('Francés', 'fr', 'fra'),
                ('Fula, Fulah, Pulaar, Pular', 'ff', 'ful'),
                ('Galicia', 'gl', 'glg'),
                ('Georgiano', 'ka', 'kat'),
                ('Alemán', 'de', 'deu'),
                ('Griego Moderno', 'el', 'ell'),
                ('Guaraní', 'gn', 'grn'),
                ('Gujarati', 'gu', 'guj'),
                ('Haitiano, creole haitiano', 'ht', 'hat'),
                ('Hausa', 'ha', 'hau'),
                ('Hebreo (moderno)', 'he', 'heb'),
                ('Herero', 'hz', 'her'),
                ('Hindi', 'hi', 'hin'),
                ('Hiri Motu', 'ho', 'hmo'),
                ('Húngaro', 'hu', 'hun'),
                ('Interlingua', 'ia', 'ina'),
                ('Indonesio', 'id', 'ind'),
                ('Interlingue', 'ie', 'ile'),
                ('Irlanda', 'ga', 'gle'),
                ('Igbo', 'ig', 'ibo'),
                ('Inupiaq', 'ik', 'ipk'),
                ('Ido', 'io', 'ido'),
                ('Islandés', 'is', 'isl'),
                ('Italiano', 'it', 'ita'),
                ('Inuktitut', 'iu', 'iku'),
                ('Japonés', 'ja', 'jpn'),
                ('Javanés', 'jv', 'jav'),
                ('Kalaallisut, Groenlandia', 'kl', 'kal'),
                ('Canarés', 'kn', 'kan'),
                ('Kanuri', 'kr', 'kau'),
                ('Cachemira', 'ks', 'kas'),
                ('Kazajstán', 'kk', 'kaz'),
                ('Khmer', 'km', 'khm'),
                ('Kikuyu, Gikuyu', 'ki', 'kik'),
                ('Kinyarwanda', 'rw', 'kin'),
                ('Kirguises, Kirguistán', 'ky', 'kir'),
                ('Komi', 'kv', 'kom'),
                ('Kongo', 'kg', 'kon'),
                ('Corea', 'ko', 'kor'),
                ('Kurdo', 'ku', 'kur'),
                ('Kwanyama, Kuanyama', 'kj', 'kua'),
                ('Latin', 'la', 'lat'),
                ('Luxemburgués, Luxemburgués', 'lb', 'ltz'),
                ('Luganda', 'lg', 'lug'),
                ('Limburgués, Limburgan, Limburger', 'li', 'lim'),
                ('Lingala', 'ln', 'lin'),
                ('Lao', 'lo', 'lao'),
                ('Lituano', 'lt', 'lit'),
                ('Luba-Katanga', 'lu', 'lub'),
                ('Letonia', 'lv', 'lav'),
                ('Manx', 'gv', 'glv'),
                ('Macedonia', 'mk', 'mkd'),
                ('Madagascar', 'mg', 'mlg'),
                ('Malayo', 'ms', 'msa'),
                ('Malayalam', 'ml', 'mal'),
                ('Maltés', 'mt', 'mlt'),
                ('Māori', 'mi', 'mri'),
                ('Maratí (Marathi)', 'mr', 'mar'),
                ('De las Islas Marshall', 'mh', 'mah'),
                ('Mongolia', 'mn', 'mon'),
                ('Nauru', 'na', 'nau'),
                ('Navajo, Navaho', 'nv', 'nav'),
                ('Noruego Bokmål', 'nb', 'nob'),
                ('Ndebele del Norte', 'nd', 'nde'),
                ('Nepali', 'ne', 'nep'),
                ('Ndonga', 'ng', 'ndo'),
                ('Noruego Nynorsk', 'nn', 'nno'),
                ('Noruego', 'no', 'nor'),
                ('Nuosu', 'ii', 'iii'),
                ('Ndebele del sur', 'nr', 'nbl'),
                ('Occitano', 'oc', 'oci'),
                ('Ojibwe, Ojibwa', 'oj', 'oji'),
                ('Antiguo eslavo eclesiástico, Iglesia eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo', 'cu', 'chu'),
                ('Oromo', 'om', 'orm'),
                ('Oriya', 'or', 'ori'),
                ('Osetia del Sur, osetio', 'os', 'oss'),
                ('Panjabi, Punjabi', 'pa', 'pan'),
                ('Pāli', 'pi', 'pli'),
                ('Persa', 'fa', 'fas'),
                ('Polaco', 'pl', 'pol'),
                ('Pashto, Pushto', 'ps', 'pus'),
                ('Portugués', 'pt', 'por'),
                ('Quechua', 'qu', 'que'),
                ('Romanche', 'rm', 'roh'),
                ('Kirundi', 'rn', 'run'),
                ('Rumania, Moldavia, Moldavan', 'ro', 'ron'),
                ('Ruso', 'ru', 'rus'),
                ('Sánscrito (samskrta)', 'sa', 'san'),
                ('Sardo', 'sc', 'srd'),
                ('Sindhi', 'sd', 'snd'),
                ('Sami del norte', 'se', 'sme'),
                ('Samoa', 'sm', 'smo'),
                ('Sango', 'sg', 'sag'),
                ('Serbio', 'sr', 'srp'),
                ('Gaélico escocés, gaélico', 'gd', 'gla'),
                ('Shona', 'sn', 'sna'),
                ('Cingalés, singalés', 'si', 'sin'),
                ('Eslovaca', 'sk', 'slk'),
                ('Esloveno', 'sl', 'slv'),
                ('Somalí', 'so', 'som'),
                ('Southern Sotho', 'st', 'sot'),
                ('Español, castellano', 'es', 'spa'),
                ('Sundanese', 'su', 'sun'),
                ('Swahili', 'sw', 'swa'),
                ('Swati', 'ss', 'ssw'),
                ('Sueco', 'sv', 'swe'),
                ('Tamil', 'ta', 'tam'),
                ('Telugu', 'te', 'tel'),
                ('Tayikistán', 'tg', 'tgk'),
                ('Tailandia', 'th', 'tha'),
                ('Tigrinya', 'ti', 'tir'),
                ('Tibetano estándar, Tibetano, Central', 'bo', 'bod'),
                ('Turkmenistán', 'tk', 'tuk'),
                ('Tagalo', 'tl', 'tgl'),
                ('Tswana', 'tn', 'tsn'),
                ('Tonga (Islas Tonga)', 'to', 'ton'),
                ('Turco', 'tr', 'tur'),
                ('Tsonga', 'ts', 'tso'),
                ('Tártara', 'tt', 'tat'),
                ('Twi', 'tw', 'twi'),
                ('Tahitian', 'ty', 'tah'),
                ('Uighur, Uyghur', 'ug', 'uig'),
                ('Ucrania', 'uk', 'ukr'),
                ('Urdu', 'ur', 'urd'),
                ('Uzbeko', 'uz', 'uzb'),
                ('Venda', 've', 'ven'),
                ('Vietnamita', 'vi', 'vie'),
                ('Volapük', 'vo', 'vol'),
                ('Valonia', 'wa', 'wln'),
                ('Galés', 'cy', 'cym'),
                ('Wolof', 'wo', 'wol'),
                ('Oeste de Frisia', 'fy', 'fry'),
                ('Xhosa', 'xh', 'xho'),
                ('Yiddish', 'yi', 'yid'),
                ('Yoruba', 'yo', 'yor'),
                ('Zhuang, Chuang', 'za', 'zha'),
                ('Zulu', 'zu', 'zul');
                
                """,  nativeQuery = true)
    void inicializarTabla();

    @Query(value = "SELECT * FROM todos_idiomas i LIMIT 1", nativeQuery = true)
    List<TodosIdiomas> verificarExistenciaDatos();

    @Query("SELECT i.idioma FROM TodosIdiomas i where i.iso_639_1 = :idioma")
    TodosIdiomas obtenerIdioma(String idioma);


}
